ACTIONS = 'AS'
LANGUAGES = 'C'
DATA_DIR = '/Users/mansourahmadi/Bank/Work/NEU/vulfinder/data/'  # Full path must be provided
PROJECTS_DIR = 'projects'
ASTS_DIR = 'asts'
SAVE_FORMAT = 'graph'  # json , graph , ast
BCS_DIR = 'bcs'
DATASETS_DIR = 'datasets'
PLOTS_DIR = 'plots'
CLUSTERING_ALGS = 'dbscancos_0.3,dbscancos_0.01'  # aff_cos dbscan_cos means
COSE_SIMILARITY_CHUNK_SIZE = 25000  # If there is 200G Ram
CLUSTERING_FEAT = 'afs_NN,afs_G2v'
SECOND_CLUSTERING = 'offline'  # offline, online
BIG_CLUSTERS_IGNORE = 200  # Size of big clusters that should be ignored from the first step clustering
#  as they might not contain useful data
CHUNK_WINDOW_SIZE = 2
SPLIT = True
SEARCH_SPACES = []  # Empty means everywhere in the projects
PROJECTS = 'juliet-test-suite'  # 'openssl-41bff72'  # 'ffmpeg-b2f0f37'  # Empty means all projects
IGNORE_COMPILE_COMMANDS = True
# UNIFIED_PROJECTS = [['test']]
FEATURE_TYPES = 'afs_NN'  # afs_G2v, afs.bb2_NN
# CLANG_LIB_DIR = '../../tools/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-16.04/lib'
CLANG_LIB_DIR = './../tools/clang+llvm-5.0.1/lib'
LLVM_CONFIG = '/usr/local/Cellar/llvm/6.0.0/bin/'
INCLUDES = ''
CLANG = 'clang'
PDG_DUMPER = ''
STAT_TYPE = 'ST'  # SS, SI, ST
STAT_SIM_TYPES = 'NN,G2v'
INCONSISTENCY_TYPE = 'check'  # check, call, type, order
SIMILARITY_THRESHOLD = 0.7
GRANULARITY = 'afs,afs.bb1,afs.bb2'
DEPENDENCY = ''  # all , odd , cdd
CALL_INCONSISTENCY = 'free,close,memset,clear,zero,remove,unlock,end,clean,cleanse,assert'
TYPE_INCONSISTENCY = 'sext,trunc'  # 'fptrunc,sext,zext,call zeroext,call signext,sitofp,uitofp,bitcast'
STORE_INCONSISTENCY = 'null'
INCONSISTENCY_QUERY_OPTIONS = 'top_10'
COUNT_CPU = 10
BENCHMARK_GROUNDTRUTH_PATH = '../iBench/'